application: s~example
version: 1
runtime: python27
threadsafe: false
api_version: 1

inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest

includes:
- titan/channel/handlers.yaml

handlers:
- url: /.*
  script: main.application
  login: required
  secure: always
